name: Build Workflow

on:
  push:
   branches: main

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          pyinstaller -F --add-data "templates;templates" --add-data "static;static" main.py
      - uses: actions/upload-artifact@v2
        with:
          name: Windows_qwiklabs
          path: dist/main.exe

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: v1.1.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}